import type { Card } from '../../types';

// Round 1 Game Cards
export const round1Cards: Card[] = [
  {
    id: "r1-1",
    type: "game",
    round: 1,
    text: "cards.round1.card1",
    mode: ["peaceful", "traditional", "chaos"],
  },
  {
    id: "r1-2",
    type: "game",
    round: 1,
    text: "cards.round1.card2",
    mode: ["peaceful", "traditional", "chaos"],
  },
  {
    id: "r1-3",
    type: "game",
    round: 1,
    text: "cards.round1.card3",
    mode: ["peaceful", "traditional", "chaos"],
  },
  {
    id: "r1-4",
    type: "game",
    round: 1,
    text: "cards.round1.card4",
    mode: ["peaceful", "traditional", "chaos"],
  },
  {
    id: "r1-5",
    type: "game",
    round: 1,
    text: "cards.round1.card5",
    mode: ["peaceful", "traditional", "chaos"],
  },
  {
    id: "r1-6",
    type: "game",
    round: 1,
    text: "cards.round1.card6",
    mode: ["peaceful", "traditional", "chaos"],
  },
  {
    id: "r1-7",
    type: "game",
    round: 1,
    text: "cards.round1.card7",
    mode: ["peaceful", "traditional", "chaos"],
  },
  {
    id: "r1-8",
    type: "game",
    round: 1,
    text: "cards.round1.card8",
    mode: ["peaceful", "traditional", "chaos"],
  },
  {
    id: "r1-9",
    type: "game",
    round: 1,
    text: "cards.round1.card9",
    mode: ["traditional", "chaos"],
  },
  {
    id: "r1-10",
    type: "game",
    round: 1,
    text: "cards.round1.card10",
    mode: ["traditional", "chaos"],
  },
  {
    id: "r1-11",
    type: "game",
    round: 1,
    text: "cards.round1.card11",
    mode: ["peaceful", "traditional", "chaos"],
  },
  {
    id: "r1-12",
    type: "game",
    round: 1,
    text: "cards.round1.card12",
    mode: ["peaceful", "traditional", "chaos"],
  },
  {
    id: "r1-13",
    type: "game",
    round: 1,
    text: "cards.round1.card13",
    mode: ["peaceful", "traditional", "chaos"],
  },
  {
    id: "r1-14",
    type: "game",
    round: 1,
    text: "cards.round1.card14",
    mode: ["traditional", "chaos"],
  },
  // Adult (18+) specific Round 1 cards
  {
    id: "r1-adult-1",
    type: "game",
    round: 1,
    text: "cards.adult.round1.card1",
    mode: ["adult"],
  },
  {
    id: "r1-adult-2",
    type: "game",
    round: 1,
    text: "cards.adult.round1.card2",
    mode: ["adult"],
  },
  {
    id: "r1-adult-3",
    type: "game",
    round: 1,
    text: "cards.adult.round1.card3",
    mode: ["adult"],
  },
  {
    id: "r1-adult-4",
    type: "game",
    round: 1,
    text: "cards.adult.round1.card4",
    mode: ["adult"],
  },
];

// Round 2 Game Cards
export const round2Cards: Card[] = [
  {
    id: "r2-1",
    type: "game",
    round: 2,
    text: "cards.round2.card1",
    mode: ["traditional", "chaos"],
  },
  {
    id: "r2-2",
    type: "game",
    round: 2,
    text: "cards.round2.card2",
    mode: ["chaos"],
  },
  {
    id: "r2-3",
    type: "game",
    round: 2,
    text: "cards.round2.card3",
    mode: ["chaos"],
  },
  {
    id: "r2-4",
    type: "game",
    round: 2,
    text: "cards.round2.card4",
    mode: ["peaceful", "traditional", "chaos"],
  },
  {
    id: "r2-5",
    type: "game",
    round: 2,
    text: "cards.round2.card5",
    mode: ["peaceful", "traditional", "chaos"],
  },
  {
    id: "r2-6",
    type: "game",
    round: 2,
    text: "cards.round2.card6",
    mode: ["peaceful", "traditional", "chaos"],
  },
  {
    id: "r2-7",
    type: "game",
    round: 2,
    text: "cards.round2.card7",
    mode: ["peaceful", "traditional", "chaos"],
  },
  {
    id: "r2-8",
    type: "game",
    round: 2,
    text: "cards.round2.card8",
    mode: ["peaceful", "traditional", "chaos"],
  },
  {
    id: "r2-9",
    type: "game",
    round: 2,
    text: "cards.round2.card9",
    mode: ["traditional", "chaos"],
  },
  {
    id: "r2-10",
    type: "game",
    round: 2,
    text: "cards.round2.card10",
    mode: ["peaceful", "traditional", "chaos"],
  },
  {
    id: "r2-11",
    type: "game",
    round: 2,
    text: "cards.round2.card11",
    mode: ["peaceful", "traditional", "chaos"],
  },
  {
    id: "r2-12",
    type: "game",
    round: 2,
    text: "cards.round2.card12",
    mode: ["chaos"],
  },
  {
    id: "r2-13",
    type: "game",
    round: 2,
    text: "cards.round2.card13",
    mode: ["peaceful", "traditional", "chaos"],
  },
  {
    id: "r2-14",
    type: "game",
    round: 2,
    text: "cards.round2.card14",
    mode: ["peaceful", "traditional", "chaos"],
  },
  {
    id: "r2-15",
    type: "game",
    round: 2,
    text: "cards.round2.card15",
    mode: ["chaos"],
  },
  {
    id: "r2-16",
    type: "game",
    round: 2,
    text: "cards.round2.card16",
    mode: ["traditional", "chaos"],
  },
  {
    id: "r2-17",
    type: "game",
    round: 2,
    text: "cards.round2.card17",
    mode: ["traditional", "chaos"],
  },
  {
    id: "r2-18",
    type: "game",
    round: 2,
    text: "cards.round2.card18",
    mode: ["chaos"],
  },
  {
    id: "r2-19",
    type: "game",
    round: 2,
    text: "cards.round2.card19",
    mode: ["peaceful", "traditional", "chaos"],
  },
  {
    id: "r2-20",
    type: "game",
    round: 2,
    text: "cards.round2.card20",
    mode: ["chaos"],
  },
  // Adult (18+) specific Round 2 cards
  {
    id: "r2-adult-1",
    type: "game",
    round: 2,
    text: "cards.adult.round2.card1",
    mode: ["adult"],
  },
  {
    id: "r2-adult-2",
    type: "game",
    round: 2,
    text: "cards.adult.round2.card2",
    mode: ["adult"],
  },
  {
    id: "r2-adult-3",
    type: "game",
    round: 2,
    text: "cards.adult.round2.card3",
    mode: ["adult"],
  },
  {
    id: "r2-adult-4",
    type: "game",
    round: 2,
    text: "cards.adult.round2.card4",
    mode: ["adult"],
  },
];

// Round 3 Game Cards
export const round3Cards: Card[] = [
  {
    id: "r3-1",
    type: "game",
    round: 3,
    text: "cards.round3.card1",
    mode: ["peaceful", "traditional", "chaos"],
  },
  {
    id: "r3-2",
    type: "game",
    round: 3,
    text: "cards.round3.card2",
    mode: ["peaceful", "traditional", "chaos"],
  },
  {
    id: "r3-3",
    type: "game",
    round: 3,
    text: "cards.round3.card3",
    mode: ["peaceful", "traditional", "chaos"],
  },
  {
    id: "r3-4",
    type: "game",
    round: 3,
    text: "cards.round3.card4",
    mode: ["traditional", "chaos"],
  },
  {
    id: "r3-5",
    type: "game",
    round: 3,
    text: "cards.round3.card5",
    mode: ["peaceful", "traditional", "chaos"],
  },
  {
    id: "r3-6",
    type: "game",
    round: 3,
    text: "cards.round3.card6",
    mode: ["peaceful", "traditional", "chaos"],
  },
  {
    id: "r3-7",
    type: "game",
    round: 3,
    text: "cards.round3.card7",
    mode: ["peaceful", "traditional", "chaos"],
  },
  {
    id: "r3-8",
    type: "game",
    round: 3,
    text: "cards.round3.card8",
    mode: ["chaos"],
  },
  {
    id: "r3-9",
    type: "game",
    round: 3,
    text: "cards.round3.card9",
    mode: ["peaceful", "traditional", "chaos"],
  },
  {
    id: "r3-10",
    type: "game",
    round: 3,
    text: "cards.round3.card10",
    mode: ["chaos"],
  },
  {
    id: "r3-11",
    type: "game",
    round: 3,
    text: "cards.round3.card11",
    mode: ["traditional", "chaos"],
  },
  {
    id: "r3-12",
    type: "game",
    round: 3,
    text: "cards.round3.card12",
    mode: ["chaos"],
  },
  {
    id: "r3-13",
    type: "game",
    round: 3,
    text: "cards.round3.card13",
    mode: ["traditional", "chaos"],
  },
  {
    id: "r3-14",
    type: "game",
    round: 3,
    text: "cards.round3.card14",
    mode: ["chaos"],
  },
  {
    id: "r3-15",
    type: "game",
    round: 3,
    text: "cards.round3.card15",
    mode: ["peaceful", "traditional", "chaos"],
  },
  {
    id: "r3-16",
    type: "game",
    round: 3,
    text: "cards.round3.card16",
    mode: ["peaceful", "traditional", "chaos"],
  },
  // Adult (18+) specific Round 3 cards
  {
    id: "r3-adult-1",
    type: "game",
    round: 3,
    text: "cards.adult.round3.card1",
    mode: ["adult"],
  },
  {
    id: "r3-adult-2",
    type: "game",
    round: 3,
    text: "cards.adult.round3.card2",
    mode: ["adult"],
  },
  {
    id: "r3-adult-3",
    type: "game",
    round: 3,
    text: "cards.adult.round3.card3",
    mode: ["adult"],
  },
  {
    id: "r3-adult-4",
    type: "game",
    round: 3,
    text: "cards.adult.round3.card4",
    mode: ["adult"],
  },
];

// Chance Cards
export const chanceCards: Card[] = [
  {
    id: "chance-1",
    type: "chance",
    round: "all",
    text: "cards.chance.save1",
    mode: ["peaceful", "traditional", "chaos"],
    isSaveCard: true,
    canNullifyAction: true,
  },
  {
    id: "chance-2",
    type: "chance",
    round: "all",
    text: "cards.chance.save2",
    mode: ["peaceful", "traditional", "chaos"],
    isSaveCard: true,
    canNullifyAction: true,
  },
  {
    id: "chance-3",
    type: "chance",
    round: "all",
    text: "cards.chance.save3",
    mode: ["peaceful", "traditional", "chaos"],
    isSaveCard: true,
  },
  {
    id: "chance-4",
    type: "chance",
    round: "all",
    text: "cards.chance.save4",
    mode: ["peaceful", "traditional", "chaos"],
    isSaveCard: true,
  },
  {
    id: "chance-5",
    type: "chance",
    round: "all",
    text: "cards.chance.rollAgain1",
    mode: ["peaceful", "traditional", "chaos"],
  },
  {
    id: "chance-6",
    type: "chance",
    round: "all",
    text: "cards.chance.rollAgain2",
    mode: ["peaceful", "traditional", "chaos"],
  },
  {
    id: "chance-7",
    type: "chance",
    round: "all",
    text: "cards.chance.food",
    mode: ["peaceful", "traditional", "chaos"],
  },
  {
    id: "chance-8",
    type: "chance",
    round: "all",
    text: "cards.chance.sing",
    mode: ["peaceful", "traditional", "chaos"],
  },
  // Adult (18+) specific chance cards
  {
    id: "chance-adult-1",
    type: "chance",
    round: "all",
    text: "cards.adult.round1.card5",
    mode: ["adult"],
  },
  {
    id: "chance-adult-2",
    type: "chance",
    round: "all",
    text: "cards.adult.round1.card6",
    mode: ["adult"],
  },
];

// All cards
export const allCards: Card[] = [
  ...round1Cards,
  ...round2Cards,
  ...round3Cards,
  ...chanceCards,
];

